app:
# Common values
  imageName: lorenzodagostinorad/go-example
  service:
    internalPort: 3000

# Envs specific values
  imageTag: latest
  replica: 1
  resources: {}
  
service:
# Envs specific values
  type: ClusterIP